version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Building the React app..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build

