version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  
    commands:
      - echo "Checking npm version..."
      - npm --version
      - echo "Updating npm to v9.2.0..."
      - npm install -g npm@9.2.0
      - echo "Installing SonarCloud scanner..."
      - npm install -g sonarqube-scanner
      - echo "Installing project dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Running SonarCloud scan..."
      - |
        sonar-scanner \
          -Dsonar.projectKey=Venu1433697_FOODY_Public \
          -Dsonar.organization=venu1433697 \
          -Dsonar.sources=src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

  build:
    commands:
      - echo "Running security audit..."
      - npm audit --audit-level=high || echo "Audit warnings found. Skipping failure..."
      - echo "Building the React app for production..."
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'
  discard-paths: yes
