version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync ./build s3://daddy3697.shop --delete

artifacts:
  files:
    - '**/*'
